export const ERROR_AUTH_USER_ALREADY_IN_USE = 'auth/email-already-in-use'
export const ERROR_AUTH_WRONG_PASSWORD = 'auth/wrong-password'
export const ERROR_AUTH_INVALID_EMAIL = 'auth/invalid-email'
export const ERROR_AUTH_USER_NOT_FOUND = 'auth/user-not-found'
export const ERROR_AUTH_WEAK_PASSWORD = 'auth/weak-password'
